version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/dockerfile.server
    ports:
      - "8080:8080"

  client:
    build:
      context: ..
      dockerfile: docker/dockerfile.client
    ports:
      - "5173:4173"