# Stage 1: Build the application
FROM maven:3.9-eclipse-temurin-24 AS build
WORKDIR /app
COPY server/demo /app
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM eclipse-temurin:24-jdk
WORKDIR /app

# Copy the built jar from the previous stage
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
